### ISSUE TITLE
projectx

### ISSUE THREAD

**Issue by EthernalVoid** [FTBTeam/FTB-Ultimate-Reloaded#100]
* **Modpack Version**: 1.0.1

* **Issue**: ProjectX textures on a brand new install

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Project X
![e](https://user-images.githubusercontent.com/45131452/53362010-7d52ac80-3939-11e9-9d8a-dc59f0737658.jpg)
![q](https://user-images.githubusercontent.com/45131452/53362012-7d52ac80-3939-11e9-912a-3e1e88557524.jpg)
![w](https://user-images.githubusercontent.com/45131452/53362013-7d52ac80-3939-11e9-9bab-6cbe94bc2345.jpg)

**Comment by ThwartAbyss54** [comment]
Oh I thought this was just because i was using Sphax. That the crystals dont have a texture, just a blank space you can hover over and get the name, and that none of the blocks have the color associated with their name. This is probably something to do with the Projectx mod more than the modpack though. He's probably still creating all the textures for it.

**Comment by tfox83** [comment]
Known issue which normally sorts on reboot. Enabling adv textures in mods config will fix it, but may cause some issues with OpenGL
