### ISSUE TITLE
Tech reborn fusion reactor energy draw, issues found in ticket 122

### ISSUE THREAD

**Issue by paznos6** [FTBTeam/FTB-Ultimate-Reloaded#137]
* **Modpack Version**: 
1.3.0

* **Issue**: 
Investigated possible fixes for ticket 122, solutions presented do not work.
The EV consumer consumes at most 2048EU/t. the IV consumer was found to consume at most 2500EU/t, as such the energy converters mod does not seem to be behaving as intended for this use.
![image](https://user-images.githubusercontent.com/48464163/54174396-9e002380-445c-11e9-8799-cb1cc5dae439.png)

this image shows the EU consumed by the IV consumer.

additionally, another user suggested using the AE2 P2P system for transfering power, but was found to have a similar limitation to 2048EU/t.
![image](https://user-images.githubusercontent.com/48464163/54174433-d43da300-445c-11e9-9e40-40d39455b604.png)
this image shows the EU consumed by the AE2 port
* **Link to Log or Crash File Paste**: 
no crash or log available

* **Is it Repeatable?**: 
yes

* **Mod/s Affected**: 
Applied energistics 2
Energy converters

* **Known Fix**: 
no known fix.

**Comment by mdgrein** [comment]
You are very correct, I was a tad hastely in my response, I do apologize.
I checked the source for the energy converters mod on github before I posted and couldn't find any hard limits anywhere so I assumed (I know, never assume, bad programmer) that they would not have any limits.

However...

The converter itself has no limits. You can convert between Tesla, RF, MJ and FE without any kind of limits (except the buffer).
One EU is turned into 4 of these buffer units meaning the default buffer of 10000 can hold a total of 2500EU.
The ratio of buffer to RF is 1:1 so the max it could output is 10k RF/tick.

In the case of EU there is unfortunetly also the limit on how much the input/output blocks can handle.
EV-consumer maxing out at 2048.

When I was going to test I noticed that there is now an IV Consumer avaliable (YAY).
That one maxes out at ~8k EU/tick so I placed one on each side and got ~32k RF/tick...
That number should be closer to 64, since 8*4=64.
When looking at the EU-reader I did notice that the average enmery in is at about half, quite exacly half actually.
The reactor is, probably, only actively outputting power to one of it's two output faces every tick (if you have something on both).
Further limiting the useful output.

Another "fun" fact is that the default buffersize hasn't changed so you can't even utilize the IV consumer/producer since the internal buffer won't let it transfer any more than 2500 EU/tick (10k RF).
Feels like a bit of an oversight imho.

The max value for the buffer is 2147483647, that translates to almost 540 million EU/tick or 2 milliard RF/tick (billion for users of the short scale).
The largest fusion reactor using the better fuel produces 15 million EU/tick so the converters could easily handle it, if they wern't gimped.

Some kind of solution that makes the fusion reactor more useful past the very smallest one would be nice.
Unless the intention is to limit it because it would be too powerful otherwise.


The limit on p2p ports for EU is a bit wierd, havn't read anything about any limitations on them.
It seems like the output is sort of round-robined in the same manner an item p2p port with several outputs work.
Might be curious enough to try and figure out why.

**Comment by tfox83** [comment]
in the next update the energy bridge buffer has been increased to 25000, thus converting up to 100k EU/t which is far more than anything required in this modpack.

**Comment by tfox83** [comment]
ok after further testing the buffer has been increased to 1 mil, this will create no limits, higher than that caused issues.

**Comment by tfox83** [comment]
included in 1.4.0 beta releasing later today
