### ISSUE TITLE
Server help

### ISSUE THREAD

**Issue by Boltfalcon** [FTBTeam/FTB-Ultimate-Reloaded#184]
Hi there,
Not really a gameplay issue, I'm just wondering how to properly set up the server with the files on the website. I want to play with a few mates and I don't know how to get it to work. Would you be able to reply with a quick guide on how to do so? Or reply with a link? I can't seem to find anything. Thank you :D

**Comment by ktole1999** [comment]
setup your base server then add mods/config/scripts from client. server files on website are override only if i recall.

**Comment by Boltfalcon** [comment]
Could you guide me through how to set up a server possibly? or if there is a guide for it?

**Comment by ktole1999** [comment]
you need to research this as there are multiple platforms for building a server. Each has their own process.

**Comment by JeNaiKe** [comment]
*  Unzip the server .zip or .rar into a folder, then launch the "server start", it will create everything you need, may take a while. 
* launch 'cmd' and do "ipconfig", get your **private** IP, should start with '192.168'. Open the "server properties" and that is the ip you give to your server. You should also open 'eula' and switch from 'false' to 'true'.
* Now, you have two choices, use hamachi or others like that, or make an Public IP. Hamachi is easy. A **public** IP is quite harded, because it switches with routers, I cannot guide you step by step in this, rather just give some blank instructions.
* Your public IP can be obtained by just googling 'ip chicken', open the website and there it is.
* Access your Router, just type in your Browser's Links bar, the thing in the top, the Router's IP, should be 192.168.1.254, try the IP's you get from the 'cmd' when you type **"arp -a"**.
* It should open a page for login and password. That I cannot help.
* Go to 'security', then 'exclusions' or 'new rule' or something of this sort. Then add your **private** IP and to the  port range '25565 to 25565'.

**Comment by tfox83** [comment]
Closing as this is not a issue with this modpack.  Check out our discord or forums if you need general help.
