### ISSUE TITLE
Superconductor cable

### ISSUE THREAD

**Issue by NiallDoherty** [FTBTeam/FTB-Ultimate-Reloaded#199]
* **Modpack Version**: beta 1.6.0

* **Issue**: 
1. The "Superconductor Cable" recipe isn't showing up in JEI when searched for, also it needs to be tweaked to use advanced machine frames from IC2 instead of Tech Reborn.
2. The cable isn't connecting to any machines from Tech Reborn or otherwise.

Issues aren't present in a pack containing only Tech Reborn and JEI, on the same forge version.

* **Mod/s Affected**: Tech Reborn, JEI?

**Comment by tfox83** [comment]
This is due to have IC2, its not meant to be placeable.

**Comment by CleymenZero** [comment]
Is this getting any attention? The issue is not resolved.

Even upgrading the AESU with superconductor upgrades to allow to transfer 1M EU/t and placing them DIRECTLY on the fusion reactor doesn't solve the issue. The AESU will only take 8192 EU/t so with 2 upgraded AESU supposedly capable of transferring 1M EU/t, you max out at 16k EU/t.

Another problem is the IDSU explodes if you try to run anything above 2048 EU/t through it even it states that input rate is 8192 EU/t.

**Comment by Chameebling-zz** [comment]
> Is this getting any attention? The issue is not resolved.
> 
> Even upgrading the AESU with superconductor upgrades to allow to transfer 1M EU/t and placing them DIRECTLY on the fusion reactor doesn't solve the issue. The AESU will only take 8192 EU/t so with 2 upgraded AESU supposedly capable of transferring 1M EU/t, you max out at 16k EU/t.
> 
> Another problem is the IDSU explodes if you try to run anything above 2048 EU/t through it even it states that input rate is 8192 EU/t.

Another problem is that with superconductor cables, the fusion reactor STILL outputs 8192 EU/t, even with the power going through the cables into 16 IV consumers.

UPDATE: Just tested that AESUs can take in more then 8192 EU/t when being inputted from another AESU with increased transfer rate, so the issue is that the fusion reactor only outputs 8192 EU/t.
