### ISSUE TITLE
No Andesite/Granite/Diorite in gen spawn. Please help :)

### ISSUE THREAD

**Issue by Tyranuss** [FTBTeam/FTB-Ultimate-Reloaded#263]
Hello, 

Not a bug, I guess this was intentional, but is there a way to obtain andesite or granite in this modpack? There is a recipe for diorite --> andesite, but it needs quartz to start, and quartz is a pain to get atm. So is there any other way to get it?

**Comment by AHrubik** [comment]
I believe it is disabled in worldgen. You can make it using the igneous extruder, use the recipes needing nether quartz found in JEI or fix it yourself using craft tweaker. The pastebin below has the script I made for my server to use cobblestone patterns rather than quartz because it seemed tedious IMO to require quartz in the volumes people want to build with.

https://pastebin.com/0incggfb

**Comment by Tyranuss** [comment]
Thank you, I'll try Igneous extruder first then. Cheers!
