### ISSUE TITLE
1.8.0 release

### ISSUE THREAD

**Issue by Shybella** [FTBTeam/FTB-Ultimate-Reloaded#288]
1.8.0 is way less crash prone than 1.7.1

can we get this set to release now? thank you for the hard work

**Comment by Crueldog** [comment]
This would be awesome if it was set to release!

**Comment by cmyers0305** [comment]
Would really appreciate releasing this update so much better than 1.7.1

**Comment by KiwiiGoose** [comment]
i totally agree ive had so much crashes on 1.7.1 and ive had 1 sofar on 1.8.0 for playing 2 weeks
Release this already

**Comment by Shybella** [comment]
I think this github has been abandoned again, time to contact slowpoke

**Comment by tfox83** [comment]
There was an issue with the syncing of versions from our launcher to twitch.  1.8.0 was set to release July 29th on our launcher.  I was on vacation from July 31st to mid Aug.  I noticed the issue and reported it, was fixed in a few days and 1.8.0 then moved to release on Twitch mid Aug.  Next time please check our launcher first before reporting.

**Comment by Shybella** [comment]
Ftb legacy launcher has been removed from the site. Only offers twitch
download

**Comment by tfox83** [comment]
Just click "linux" under the download button.  its a universal JAR that works on any OS
