### ISSUE TITLE
Probable Error In Iridium Reinforced Plate Crafting

### ISSUE THREAD

**Issue by RedCorpIndustry** [FTBTeam/FTB-Ultimate-Reloaded#298]
* **Modpack Version**: Version 1.8.0

* **Issue**:Iridium reinforced plates can be crafted from Magnalium plates. I believe this is likely an error, because Magnalium plates are cheaper than the proper way of crafting them, with iridium alloy ingots in an implosion compressor. Secondly, Tech Reborn Iridium Alloy Plates cannot be crafted into IC2 Iridium Reinforced Plates. It appears to be a faulty CraftTweaker script, as the recipe says it was added by CraftTweaker.

* **Link to Log or Crash File Paste**: Not Applicable

* **Is it Repeatable?**: Just look at the recipe for Iridium Reinforced Plates.

* **Mod/s Affected**: Tech Reborn, Industrial Craft 2, CraftTweaker

* **Known Fix**: Fix using CraftTweaker.

**Comment by NiallDoherty** [comment]
Also advanced alloy can be crafted from a refined iron plate...

**Comment by Soitora** [comment]
This was closed (11 hours ago as of writing), can I assume this will be patched shortly? It made me completely stop wanting to play as the only way I could get Iridium was through very cheap methods (converting Magnalium plates 1:1 in crafting slot), unless you can with the Implosion Compression (doesn't say in the JEI mod that you can).

Also what @NiallDoherty wrote, being able to get Advanced Alloy from 1:1 converting a refined Iron Plate is also way too OP.

**Comment by RedCorpIndustry** [comment]
I will try and see if it is fixed in 1.9.0, i will report back when done testing

**Comment by Soitora** [comment]
It isn't fixed, it took me literally 20 seconds in a text editor with the `ic2.zs` file to fix both these issues (except I couldn't find how to hide the Metal Press recipes), yet this issue has been public for almost a month now.

It's the lines `33`, `34`, `42` and `43`.

The issue is that the `ic2.zs` file is configured to trade between the **IC2's Iridium Reinforced Plate** (`ic2:crafting:4`) and **Tech Reborn's Iridum Alloy Plate** (`techreborn:plates:38`), except it doesn't use the correct ID for the **Iridum Alloy Plate**, it uses the ID for **Magnalium Plates** (`techreborn:plates:37`).

The issue for the **Advanced Alloys** is almost the exact same, it tries to switch (`ic2:crafting:3`) with (`techreborn:plates:35`), I'm not sure which this really should be but it *definitely* shouldn't be the **Refined Iron Plate**. In my own server I switched it to **Magnalium Plates** (`techreborn:plates:37`) as those were almost as hard to make as **Mixed Metal Ingots**.

**EDIT:** After looking this up in-game I think that **Advanced Alloy** (`ic2:crafting:3`) is supposed to be interchanged with **Advanced Alloy Plate** (`techreborn:plates:36`), I didn't find it at first because it actually doesn't show up in **JEI** (neither did **Advanced Alloy Ingot** `techreborn:ingot:20` which it's made out of) at all unless you find the recipe while browsing recipe modes...
