### ISSUE TITLE
Project Red pipes/chips prohibitively expensive.  Suggest increasing illumar return.

### ISSUE THREAD

**Issue by nan0bug00** [FTBTeam/FTB-Ultimate-Reloaded#34]
* **Modpack Version**: 1.0.1

* **Issue**: The cost of the illumar needed to set up a Project Red logistics system is insane.   It would take stacks upon stacks of dyes to get anything beyond the most basic setup going.    The dye trees/stained saplings aren't in the pack, unsure if this was removed from the mod or just taken out of the pack, but this leaves you relying on RNG (flower forest biome) or needing to set up a significant amount of infrastructure to do anything useful.  Most pipes need 2 chips to be useful, each chip takes 4 illumar which takes 2 dye per.  So you're looking at 16 dye per "smart" pipe.  If you want to do anything more than an incredibly basic setup, this is absurdly expensive in light of what it costs to get AE2 going.

Ways to get the dyes that I have considered:

1.  Industrial foregoing dye mixer.  Which requires making plastics first, Pink Slime  for the lenses, which requires a mob grinder, which requires essence and power and would still require a bunch of flowers.  It's a whole lot of infrastructure on the front end just to get a little more dye out of each flower.

2.  Get lucky with a flower forest.  I have explored pretty far from my base in every direction and found none.  Given the lack of easy ways to get around and no natures compass, this is unreasonable.

3.  Vanilla redstone contraption, requires ridiculous amounts of bonemeal/fertilizer, not much return for the cost, unless you get lucky and find the aforementioned flower forest.

4.  Dye sheep, pulverize colored wool, get one dye per wool.   Unless you set up massive server killing sheep farms this would be a very slow grind, especially compared to the ease of setting up AE2.

* **Known Fix**: Suggest changing recipe for illumar to return three illumar per craft at least.  Or add the dye trees back in if that's possible.

**Comment by tfox83** [comment]
In my testing playthrough I had a auto sheep farm with a couple sheep of each color and they were auto sheared instead of killed, ran wool through pulverizer.  I didnt have any issues.  If you feel there are too expensive still please suggest this to the mod developer for project red.  We thought they were fine and encouraged infrastructure.

**Comment by LemADEC** [comment]
Industrial Foregoing dye mixer doesn't give better output from what I've seen, please elaborate.

Other sources of dyes to consider: Binnie's bees, Vanilla farms (bones & cactus), Thermal Pulverizer (4x output).

Project red pipes & chips aren't early game, and they are also impacting TPS.
All in all, those recipe costs looks fine to me.

**Comment by nan0bug00** [comment]
AE2 shouldn't be early game then, since it's a far more powerful solution for requesting/autocrafting, but with the way it's been dumbed down in this pack it just funnels everyone into AE2 instead of trying to do something that isn't a magic block solution.  Once you grow some sugarcane for paper to trade with villagers, take a trip to the nether and do  a short overworld cave run for certus quartz you're ready to go with an AE2 system.  In order to do anything meangingful with Project Red you've got to invest way more time and resources into setting up a bunch of infrastructure first.

It just seems backwards to me, especially when viewed in contrast with the rest of the pack.

**Comment by LemADEC** [comment]
I guess you mean AE2 is configured to use the (legacy) Cutting knife instead of the press. Indeed, this makes you skip the exploration for the press and extra crafting step in the inscriber.
Practically, on our public servers, players first go to mod is largely AE2 even with a gated recipe; also, they are pretty to share their presses, so it's not really a barrier. In that aspect, ProjectRed would need to be way cheaper and gating access to AE2 autocrafting to be even considered by players for automation.

Now, as a server owner, because ProjectRed is bad for TPS, I'm fine with existing recipes because it's not good for the server when players use that mod extensively.

**Comment by tfox83** [comment]
Alot of this was done to follow Ultimate in 1.4.7  I do agree AE is easy, but that is the way it was back then :)  As far as dyes, those are easy in modded MC, its not really a gate, a colored sheep farm and pulverizer is earlier for most than the power set up needed for an AE system.
