### ISSUE TITLE
There is something wrong my inventory 

### ISSUE THREAD

**Issue by HeyIMnew** [FTBTeam/FTB-Ultimate-Reloaded#37]
This is 1.01. 
so can anyone help?
![eqfwwf](https://user-images.githubusercontent.com/20028397/52849108-dc970c80-3142-11e9-8911-fc7ff84c7260.PNG)

**Comment by tfox83** [comment]
Hmm can't say I have seen that one before.  Maybe something funky with JEI?  Is it just a visual glitch? Also have you added any mods like Optifine?  Are you assigning at least 4GB to Java?

**Comment by nan0bug00** [comment]
There is a player on my server having similar issues.  Cobblestone on his head like a helmet, all sorts of weird behavior.  It appears to be connected to Railcraft multiblock structures like the boilers, coke oven and blast furnace, happened to him twice, both while moving or building RC multiblocks.

I wish I had more information for you, I encouraged him to take screenshots and copy his logs when it happens in the hopes that we can figure out what's going on, but it hasn't happened since.

Edit:

Actually here is a pic he sent me on discord.  

![unknown](https://user-images.githubusercontent.com/8329580/52930171-6a2a5600-3315-11e9-8428-183c8c517b70.png)

**Comment by tfox83** [comment]
Its been a known issue when dealing with things like servos and such.  Just a simple relog fixes the issue until a dev fixes it properly.
