### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by RickERMc** [FTBTeam/FTB-Ultimate-Reloaded#68]
* **Modpack Version**: FTB Ultimate Reloaded v1.0.1

* **Issue**: Server crashing at random

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/f79f7b59

* **Is it Repeatable?**: no

* **Mod/s Affected**: N/A

* **Known Fix**: N/A

**Comment by LemADEC** [comment]
Your server has 8GB allocated with a single player. Chances are you host can't handle it. Reduce it to the recommended 4GB.

**Comment by Dyneteve** [comment]
@LemADEC What you said makes no sense why reduce ram lol? When you can just get more more always is better

**Comment by LemADEC** [comment]
RAM is shared with all processes running on your computer. Allocating too much to one process (Minecraft in this case), will starve others, forcing system to use disk memory. The latest is much slower, lagging the whole computer, and eventually crashing since not all programs support such memory.
Also, adding more RAM to a Java process can cause lag spikes due to huge amount of memory to reorganize and free during GC cycle.
It's generally good to add more RAM to your computer. It's generally not the case for programs themselves.
