### ISSUE TITLE
Cannot transfer power from Quantum solar panel - transfer rate too high

### ISSUE THREAD

**Issue by loneztar** [FTBTeam/FTB-Ultimate-Reloaded#79]
* **Modpack Version**: <**Version 1.0.1**>

* **Issue**: <**Quantum solar panel power cannot be transferred as there is no cable with high enough transfer rate to support it - everything explodes**>

* **Link to Log or Crash File Paste**: <**No crash present**>

* **Is it Repeatable?**: <**Not applicable**>

* **Mod/s Affected**: <**Advanced Solar Panels**>

* **Known Fix**: <**No known/suggested fix**>

**Comment by Argo11** [comment]
Yea...this is just because they have Tier 5 power. You should be able to use Transformers to lower its...power level(yea lets go with that) so that you can safely transfer it. This is a mechanic of IC2, as well as several mods with power Tiers(like TechReborn and Immersive Engineering).

granted...im not sure there is a transformer capable. T1 is LV, T2 is MV, T3 is HV, and tier 4 is EV. But I have no idea what tier 5 is, but either way I don't recall anything being able to transform that.

**Comment by tfox83** [comment]
Hmm yea, um for now I wouldnt go higher than the tier 4 solar.  I may look at disabling the quantum solar as it makes no since not being able to use it.

**Comment by tfox83** [comment]
Wait
#IV energy converters
mods.jei.JEI.removeAndHide(<energyconverters:energy_consumer_eu:4>);
mods.jei.JEI.removeAndHide(<energyconverters:energy_producer_eu:4>);
this is the highest tier energy converter that is tier 5.  I could reeable these guys and that would allow you to at least convert its power.  Still not really a good idea it you want direct EU.

**Comment by tfox83** [comment]
After some testing I think it is better to remove the tier 5 solar as it cant be used with its own power.  I will put a place holder recipe in place to allow you to get back 8 of the tier 4 solars.  But not be able to craft any more of the tier 5.

**Comment by tfox83** [comment]
Ok the solar has been removed from JEI and crafting disabled, also tool tipped to let you know you can get 8 of the tier 4 solars from it for the people that have already made them.  This will be in next update.

**Comment by LoveAlmstrom** [comment]
sadface I just made the quantum solar panel on Slows server
