### ISSUE TITLE
Invar Plate in IC2 Compressor

### ISSUE THREAD

**Issue by ThwartAbyss54** [FTBTeam/FTB-Ultimate-Reloaded#92]
* **Modpack Version**: 1.1.1 same was happening on 1.0.1

* **Issue**:  Invar plates can't be made in the ic2 compressor. Iron etc can but you cant insert invar ingots into it. Invar plates cant be made in the rolling machine either. Only the compactor from TE

* **Is it Repeatable?**:  Yes try putting an invar ingot into the ic2 compressor, i believe this is easy to fix and was just letting you know! :)

**Comment by isavegas** [comment]
Steel plates also cannot be made in the IC2 compressor. I believe it is a simple ore dictionary issue, as there IS a recipe for it. The issue seems to be rooted in the fact that it wants IC2 steel ingots, which are neither obtainable from the Thermal Foundation ingots that are given from the industrial blast furnace nor the Railcraft ingots that are obtained from converting steel blocks into ingots.

**Comment by tfox83** [comment]
both steel and invar plates have been added to next update, thanks
